turtlebot_highlevel_controller:
        scan_sub_topic: 'scan'
        filtered_scan_pub_topic: 'filtered_scan'
        twist_pub_topic: 'cmd_vel'
        marker_pub_topic: 'marker_pillar'
        queue_size: 1
        base_linear_speed: 0.25
        base_angular_speed: 0.25
        p_factor: 0.01
        stopping_dist: 0.3
